
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package lema;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int transp = 18;
  public static final int pr_const = 2;
  public static final int dif = 23;
  public static final int pr_sino = 55;
  public static final int ll_ab = 11;
  public static final int mod = 17;
  public static final int a_suma = 37;
  public static final int cor_ce = 10;
  public static final int pr_resta = 33;
  public static final int pr_suma = 32;
  public static final int coma = 65;
  public static final int pr_selector = 59;
  public static final int igual = 31;
  public static final int neg = 30;
  public static final int pr_inv = 36;
  public static final int real = 49;
  public static final int a_resta = 38;
  public static final int a_div = 40;
  public static final int par_ab = 7;
  public static final int octa_r = 45;
  public static final int ll_ce = 12;
  public static final int pr_real = 5;
  public static final int numero = 48;
  public static final int pr_mientras = 56;
  public static final int pr_entero = 4;
  public static final int menos = 14;
  public static final int menor = 24;
  public static final int EOF = 0;
  public static final int punto_coma = 64;
  public static final int ident = 22;
  public static final int prod = 15;
  public static final int mayor_igual = 27;
  public static final int pr_si = 54;
  public static final int octa_e = 44;
  public static final int mas = 13;
  public static final int pr_default = 62;
  public static final int error = 1;
  public static final int a_mod = 41;
  public static final int mayor = 25;
  public static final int a_prod = 39;
  public static final int premas = 67;
  public static final int pr_leer = 51;
  public static final int pr_prod = 34;
  public static final int pr_para = 58;
  public static final int premenos = 68;
  public static final int menor_igual = 26;
  public static final int id = 66;
  public static final int par_ce = 8;
  public static final int inv = 19;
  public static final int pr_vacio = 3;
  public static final int y = 28;
  public static final int pr_saltar = 60;
  public static final int pr_principal = 53;
  public static final int pr_caso = 61;
  public static final int pr_hacer = 57;
  public static final int o = 29;
  public static final int cor_ab = 9;
  public static final int pr_cadena = 6;
  public static final int decr = 21;
  public static final int hexa_r = 47;
  public static final int incr = 20;
  public static final int err = 69;
  public static final int pr_mostrar = 52;
  public static final int div = 16;
  public static final int pr_retornar = 63;
  public static final int pr_transp = 35;
  public static final int sig_pun = 43;
  public static final int cadena = 50;
  public static final int hexa_e = 46;
  public static final int sig_int = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "pr_const",
  "pr_vacio",
  "pr_entero",
  "pr_real",
  "pr_cadena",
  "par_ab",
  "par_ce",
  "cor_ab",
  "cor_ce",
  "ll_ab",
  "ll_ce",
  "mas",
  "menos",
  "prod",
  "div",
  "mod",
  "transp",
  "inv",
  "incr",
  "decr",
  "ident",
  "dif",
  "menor",
  "mayor",
  "menor_igual",
  "mayor_igual",
  "y",
  "o",
  "neg",
  "igual",
  "pr_suma",
  "pr_resta",
  "pr_prod",
  "pr_transp",
  "pr_inv",
  "a_suma",
  "a_resta",
  "a_prod",
  "a_div",
  "a_mod",
  "sig_int",
  "sig_pun",
  "octa_e",
  "octa_r",
  "hexa_e",
  "hexa_r",
  "numero",
  "real",
  "cadena",
  "pr_leer",
  "pr_mostrar",
  "pr_principal",
  "pr_si",
  "pr_sino",
  "pr_mientras",
  "pr_hacer",
  "pr_para",
  "pr_selector",
  "pr_saltar",
  "pr_caso",
  "pr_default",
  "pr_retornar",
  "punto_coma",
  "coma",
  "id",
  "premas",
  "premenos",
  "err"
  };
}

