package lema;

public enum Token
{
    /* COMENTARIOS */
    COMENT_AB, COMENT_CE,
    
    /* IDENTIFICADOR */
    ID,
    
    /* CONSTANTES*/
    PR_CONST,
    
    /* TIPOS DE DATOS BASICOS */
    PR_VACIO, PR_ENTERO, PR_REAL, PR_CADENA,
    
    /* OPERADORES DE AGRUPACION */
    PAR_AB, PAR_CE, LL_AB, LL_CE,
    
    /* OPERADORES ARITMETICOS */
    MAS, MENOS, PROD, DIV, MOD, TRANSP, INV, INCR, DECR, 
    PR_SUMA, PR_RESTA, PR_PROD, PR_TRANSP, PR_INV,
    
    /* OPERADORES DE RELACION */
    IDENT, DIF, MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL,
    
    /* OPERADORES LOGICOS */
    Y, O, NEG,
    
    /* OPERADORES DE ASIGNACION */
    IGUAL, A_SUMA, A_RESTA, A_PROD, A_DIV,
    
    /* OPERADOR CONDICIONAL */
    SIG_INT, SIG_PUN,
    
    /* OPERADOR DE ACCESO */
    COR_AB, COR_CE, 
    
    /* DATOS */
    NUMERO, REAL, CADENA,
    
    /* INSTRUCCIONES ENTRADA / SALIDA */
    PR_LEER, PR_MOSTRAR,
    
    /* DECLARACION DE FUNCIONES */
    FINAL, COMA, PR_RETORNAR,
    
    /* SENTENCIAS CONDICIONALES */
    PR_SI, PR_SINO,
    
    /* SENTENCIAS DE REPETICION */
    PR_MIENTRAS, PR_HACER, PR_PARA,
    
    /* SENTENCIAS DE SELECCION MULTIPLE */
    PR_SELECTOR, PR_SALTAR, PR_CASO, PR_DEFAULT,
    
    /* MENU PRINCIPAL*/
    PR_PRINCIPAL,
    
    /* ERROR */
    ERROR;
}