/* The following code was generated by JFlex 1.4.3 on 12/06/15 0:49 */

package lema;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/06/15 0:49 from the specification file
 * <tt>K:/CO/Analizador Lexico/LeMa/src/lema/lexico.flex</tt>
 */
class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\6\2\0\1\3\22\0\1\3\1\40\1\52\2\0"+
    "\1\30\1\43\1\31\1\22\1\23\1\5\1\26\1\54\1\27\1\51"+
    "\1\4\12\2\1\46\1\53\1\41\1\37\1\42\1\45\1\0\32\1"+
    "\1\47\1\0\1\50\1\32\1\1\1\0\1\15\1\1\1\7\1\36"+
    "\1\17\1\56\1\1\1\55\1\16\2\1\1\21\1\34\1\11\1\10"+
    "\1\35\1\1\1\20\1\12\1\13\1\33\1\14\4\1\1\24\1\44"+
    "\1\25\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\10\2"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\2\2\1\20\1\21\1\22\1\23\2\1\1\24"+
    "\1\25\1\26\1\27\1\1\1\30\1\31\1\2\2\0"+
    "\1\32\1\33\3\2\1\34\10\2\1\35\1\36\1\37"+
    "\1\40\5\2\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\0\1\47\1\2\1\50\1\0\25\2\1\4\1\2"+
    "\1\51\1\2\1\52\1\2\1\53\6\2\1\54\1\55"+
    "\3\2\1\56\3\2\1\57\3\2\1\60\2\2\1\61"+
    "\6\2\1\62\1\63\3\2\1\64\10\2\1\65\1\2"+
    "\1\66\4\2\1\67\1\2\1\70\1\71\1\2\1\72"+
    "\3\2\1\73\1\2\1\74\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\57\0\274\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\57"+
    "\0\57\0\57\0\57\0\u0292\0\u02c1\0\57\0\57\0\57"+
    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439"+
    "\0\57\0\57\0\57\0\57\0\u0468\0\57\0\57\0\u0497"+
    "\0\u04c6\0\u04f5\0\57\0\57\0\u0524\0\u0553\0\u0582\0\u05b1"+
    "\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729"+
    "\0\57\0\57\0\57\0\57\0\u0758\0\u0787\0\u07b6\0\u07e5"+
    "\0\u0814\0\57\0\57\0\57\0\57\0\57\0\57\0\u0468"+
    "\0\u0468\0\u0843\0\u04c6\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6"+
    "\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e"+
    "\0\u0c4d\0\u04f5\0\u0c7c\0\136\0\u0cab\0\136\0\u0cda\0\136"+
    "\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\136\0\136"+
    "\0\u0e23\0\u0e52\0\u0e81\0\136\0\u0eb0\0\u0edf\0\u0f0e\0\136"+
    "\0\u0f3d\0\u0f6c\0\u0f9b\0\136\0\u0fca\0\u0ff9\0\136\0\u1028"+
    "\0\u1057\0\u1086\0\u10b5\0\u10e4\0\u1113\0\136\0\136\0\u1142"+
    "\0\u1171\0\u11a0\0\136\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b"+
    "\0\u12ba\0\u12e9\0\u1318\0\136\0\u1347\0\136\0\u1376\0\u13a5"+
    "\0\u13d4\0\u1403\0\136\0\u1432\0\136\0\136\0\u1461\0\136"+
    "\0\u1490\0\u14bf\0\u14ee\0\136\0\u151d\0\136\0\136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\5\1\10"+
    "\2\3\1\11\1\12\1\13\1\3\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\3\1\31\1\32\1\3\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\2\1\45\1\46\1\47\1\50\1\3\60\0\2\3"+
    "\4\0\13\3\11\0\4\3\16\0\2\3\2\0\1\4"+
    "\46\0\1\51\12\0\1\52\31\0\1\53\56\0\1\54"+
    "\20\0\2\3\4\0\1\3\1\55\4\3\1\56\4\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\6\3"+
    "\1\57\1\60\1\61\2\3\11\0\1\62\3\3\16\0"+
    "\2\3\1\0\2\3\4\0\11\3\1\63\1\3\11\0"+
    "\4\3\16\0\2\3\1\0\2\3\4\0\6\3\1\64"+
    "\4\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\2\3\1\65\10\3\11\0\4\3\16\0\2\3\1\0"+
    "\2\3\4\0\2\3\1\66\10\3\11\0\4\3\16\0"+
    "\2\3\1\0\2\3\4\0\10\3\1\67\2\3\11\0"+
    "\4\3\16\0\2\3\1\0\2\3\4\0\10\3\1\70"+
    "\2\3\11\0\4\3\16\0\2\3\26\0\1\71\10\0"+
    "\1\72\46\0\1\73\7\0\1\74\20\0\2\3\4\0"+
    "\1\3\1\75\5\3\1\76\3\3\11\0\4\3\16\0"+
    "\2\3\1\0\2\3\4\0\1\3\1\77\4\3\1\100"+
    "\2\3\1\101\1\3\11\0\4\3\16\0\2\3\37\0"+
    "\1\102\56\0\1\103\56\0\1\104\56\0\1\105\62\0"+
    "\1\106\57\0\1\107\12\0\6\110\1\0\43\110\1\111"+
    "\4\110\1\0\2\3\4\0\6\3\1\112\4\3\11\0"+
    "\4\3\16\0\2\3\2\0\1\113\54\0\5\52\1\114"+
    "\51\52\1\0\2\3\4\0\2\3\1\115\10\3\11\0"+
    "\4\3\16\0\2\3\1\0\2\3\4\0\3\3\1\116"+
    "\7\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\12\3\1\117\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\2\3\1\120\10\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\12\3\1\121\11\0\4\3\16\0"+
    "\2\3\1\0\2\3\4\0\13\3\11\0\1\3\1\122"+
    "\2\3\16\0\2\3\1\0\2\3\4\0\6\3\1\123"+
    "\4\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\1\124\12\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\5\3\1\125\5\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\4\3\1\126\6\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\3\3\1\127\1\130"+
    "\1\3\1\131\4\3\11\0\4\3\16\0\2\3\1\0"+
    "\2\3\4\0\10\3\1\132\2\3\11\0\4\3\16\0"+
    "\2\3\1\0\2\3\4\0\3\3\1\133\7\3\11\0"+
    "\4\3\16\0\2\3\1\0\2\3\4\0\10\3\1\134"+
    "\2\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\11\3\1\135\1\3\11\0\4\3\16\0\2\3\1\0"+
    "\2\3\4\0\11\3\1\136\1\3\11\0\4\3\16\0"+
    "\2\3\1\0\2\3\4\0\1\3\1\137\5\3\1\140"+
    "\3\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\1\141\12\3\11\0\4\3\16\0\2\3\4\52\1\142"+
    "\1\114\51\52\1\0\2\3\4\0\3\3\1\143\7\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\1\3"+
    "\1\144\11\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\4\3\1\145\6\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\1\3\1\146\11\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\10\3\1\147\2\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\6\3"+
    "\1\150\4\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\2\3\1\151\10\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\7\3\1\152\3\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\10\3\1\153\2\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\10\3"+
    "\1\154\2\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\4\3\1\155\6\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\1\3\1\156\11\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\12\3\1\157\11\0"+
    "\4\3\16\0\2\3\1\0\2\3\4\0\11\3\1\160"+
    "\1\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\4\3\1\161\6\3\11\0\4\3\16\0\2\3\1\0"+
    "\2\3\4\0\2\3\1\162\10\3\11\0\4\3\16\0"+
    "\2\3\1\0\2\3\4\0\13\3\11\0\3\3\1\163"+
    "\16\0\2\3\1\0\2\3\4\0\6\3\1\164\4\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\13\3"+
    "\11\0\3\3\1\165\16\0\2\3\1\0\2\3\4\0"+
    "\2\3\1\166\10\3\11\0\4\3\16\0\2\3\1\0"+
    "\2\3\4\0\10\3\1\167\2\3\11\0\4\3\16\0"+
    "\2\3\1\0\2\3\4\0\4\3\1\170\6\3\11\0"+
    "\4\3\16\0\2\3\1\0\2\3\4\0\6\3\1\171"+
    "\4\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\1\172\12\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\3\3\1\173\7\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\1\3\1\174\11\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\11\3\1\175\1\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\11\3"+
    "\1\176\1\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\6\3\1\177\4\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\11\3\1\200\1\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\11\3\1\201\1\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\4\3"+
    "\1\202\6\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\10\3\1\203\2\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\13\3\11\0\1\204\3\3\16\0"+
    "\2\3\1\0\2\3\4\0\1\205\12\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\11\3\1\206\1\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\11\3"+
    "\1\207\1\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\4\3\1\210\6\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\13\3\11\0\2\3\1\211\1\3"+
    "\16\0\2\3\1\0\2\3\4\0\3\3\1\212\7\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\1\3"+
    "\1\213\11\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\2\3\1\214\10\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\6\3\1\215\4\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\11\3\1\216\1\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\13\3"+
    "\11\0\4\3\16\0\1\3\1\217\1\0\2\3\4\0"+
    "\1\220\12\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\7\3\1\221\3\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\1\3\1\222\11\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\13\3\11\0\1\223"+
    "\3\3\16\0\2\3\1\0\2\3\4\0\6\3\1\224"+
    "\4\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\6\3\1\225\4\3\11\0\4\3\16\0\2\3\1\0"+
    "\2\3\4\0\11\3\1\226\1\3\11\0\4\3\16\0"+
    "\2\3\1\0\2\3\4\0\6\3\1\227\4\3\11\0"+
    "\4\3\16\0\2\3\1\0\2\3\4\0\10\3\1\230"+
    "\2\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\4\3\1\231\6\3\11\0\4\3\16\0\2\3\1\0"+
    "\2\3\4\0\13\3\11\0\2\3\1\232\1\3\16\0"+
    "\2\3\1\0\2\3\4\0\11\3\1\233\1\3\11\0"+
    "\4\3\16\0\2\3\1\0\2\3\4\0\10\3\1\234"+
    "\2\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\11\3\1\235\1\3\11\0\4\3\16\0\2\3\1\0"+
    "\2\3\4\0\3\3\1\236\7\3\11\0\4\3\16\0"+
    "\2\3\1\0\2\3\4\0\1\237\12\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\1\3\1\240\11\3"+
    "\11\0\4\3\16\0\2\3\1\0\2\3\4\0\6\3"+
    "\1\241\4\3\11\0\4\3\16\0\2\3\1\0\2\3"+
    "\4\0\3\3\1\242\7\3\11\0\4\3\16\0\2\3"+
    "\1\0\2\3\4\0\4\3\1\243\6\3\11\0\4\3"+
    "\16\0\2\3\1\0\2\3\4\0\12\3\1\244\11\0"+
    "\4\3\16\0\2\3\1\0\2\3\4\0\4\3\1\245"+
    "\6\3\11\0\4\3\16\0\2\3\1\0\2\3\4\0"+
    "\1\3\1\246\11\3\11\0\4\3\16\0\2\3\1\0"+
    "\2\3\4\0\6\3\1\247\4\3\11\0\4\3\16\0"+
    "\2\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5452];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\12\1\4\11\2\1\3\11"+
    "\10\1\4\11\1\1\2\11\1\1\2\0\2\11\14\1"+
    "\4\11\5\1\6\11\1\0\3\1\1\0\133\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 37: 
          { return symbol(sym.y);
          }
        case 62: break;
        case 46: 
          { return symbol(sym.pr_para);
          }
        case 63: break;
        case 31: 
          { return symbol(sym.decr);
          }
        case 64: break;
        case 43: 
          { return symbol(sym.pr_suma);
          }
        case 65: break;
        case 13: 
          { return symbol(sym.mod);
          }
        case 66: break;
        case 24: 
          { return symbol(sym.punto_coma);
          }
        case 67: break;
        case 41: 
          { return symbol(sym.pr_caso);
          }
        case 68: break;
        case 42: 
          { return symbol(sym.pr_sino);
          }
        case 69: break;
        case 28: 
          { return symbol(sym.pr_si);
          }
        case 70: break;
        case 29: 
          { return symbol(sym.incr);
          }
        case 71: break;
        case 38: 
          { return symbol(sym.o);
          }
        case 72: break;
        case 35: 
          { return symbol(sym.menor_igual);
          }
        case 73: break;
        case 6: 
          { return symbol(sym.prod);
          }
        case 74: break;
        case 3: 
          { return symbol(sym.numero, yytext());
          }
        case 75: break;
        case 39: 
          { return symbol(sym.cadena, yytext());
          }
        case 76: break;
        case 55: 
          { return symbol(sym.pr_selector);
          }
        case 77: break;
        case 26: 
          { return symbol(sym.a_div);
          }
        case 78: break;
        case 17: 
          { return symbol(sym.neg);
          }
        case 79: break;
        case 40: 
          { return symbol(sym.real, yytext());
          }
        case 80: break;
        case 7: 
          { return symbol(sym.par_ab);
          }
        case 81: break;
        case 22: 
          { return symbol(sym.cor_ab);
          }
        case 82: break;
        case 56: 
          { return symbol(sym.pr_retornar);
          }
        case 83: break;
        case 32: 
          { return symbol(sym.a_resta);
          }
        case 84: break;
        case 1: 
          { return symbol(sym.error_lex, yytext());
          }
        case 85: break;
        case 52: 
          { return symbol(sym.pr_entero);
          }
        case 86: break;
        case 9: 
          { return symbol(sym.ll_ab);
          }
        case 87: break;
        case 21: 
          { return symbol(sym.sig_pun);
          }
        case 88: break;
        case 59: 
          { return symbol(sym.pr_principal);
          }
        case 89: break;
        case 27: 
          { return symbol(sym.a_prod);
          }
        case 90: break;
        case 12: 
          { return symbol(sym.menos);
          }
        case 91: break;
        case 19: 
          { return symbol(sym.mayor);
          }
        case 92: break;
        case 45: 
          { return symbol(sym.pr_leer);
          }
        case 93: break;
        case 11: 
          { return symbol(sym.mas);
          }
        case 94: break;
        case 47: 
          { return symbol(sym.pr_const);
          }
        case 95: break;
        case 14: 
          { return symbol(sym.transp);
          }
        case 96: break;
        case 18: 
          { return symbol(sym.menor);
          }
        case 97: break;
        case 15: 
          { return symbol(sym.inv);
          }
        case 98: break;
        case 4: 
          { /* Ignorar */
          }
        case 99: break;
        case 61: 
          { return symbol(sym.pr_transp);
          }
        case 100: break;
        case 16: 
          { return symbol(sym.igual);
          }
        case 101: break;
        case 49: 
          { return symbol(sym.pr_resta);
          }
        case 102: break;
        case 57: 
          { return symbol(sym.pr_mientras);
          }
        case 103: break;
        case 44: 
          { return symbol(sym.pr_real);
          }
        case 104: break;
        case 30: 
          { return symbol(sym.a_suma);
          }
        case 105: break;
        case 60: 
          { return symbol(sym.pr_default);
          }
        case 106: break;
        case 54: 
          { return symbol(sym.pr_mostrar);
          }
        case 107: break;
        case 58: 
          { return symbol(sym.pr_prod);
          }
        case 108: break;
        case 20: 
          { return symbol(sym.sig_int);
          }
        case 109: break;
        case 34: 
          { return symbol(sym.dif);
          }
        case 110: break;
        case 50: 
          { return symbol(sym.pr_hacer);
          }
        case 111: break;
        case 36: 
          { return symbol(sym.mayor_igual);
          }
        case 112: break;
        case 8: 
          { return symbol(sym.par_ce);
          }
        case 113: break;
        case 23: 
          { return symbol(sym.cor_ce);
          }
        case 114: break;
        case 25: 
          { return symbol(sym.coma);
          }
        case 115: break;
        case 48: 
          { return symbol(sym.pr_vacio);
          }
        case 116: break;
        case 2: 
          { return symbol(sym.id, yytext());
          }
        case 117: break;
        case 53: 
          { return symbol(sym.pr_inv);
          }
        case 118: break;
        case 33: 
          { return symbol(sym.ident);
          }
        case 119: break;
        case 10: 
          { return symbol(sym.ll_ce);
          }
        case 120: break;
        case 51: 
          { return symbol(sym.pr_saltar);
          }
        case 121: break;
        case 5: 
          { return symbol(sym.div);
          }
        case 122: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
